name = "Matthew Polak"
phone = "+1 (519) 362-9413"
location = "Ontario, Canada"

email = "me@matteopolak.com"
website = "matteopolak.com"
github = "matteopolak"
linkedin = "matteo-polak"

achievements = [
	"2023 #link(\"https://hack-the-hill.devpost.com\", \"Hack the Hill\") Hackathon, 1st (Ciena track), Best Developer Experience, Best Cybersecurity Project",
	"2023 #link(\"https://all-in-hackathon.devpost.com\", \"MLH x {all in}\") Hackathon, 1st Overall",
	"2023 #link(\"https://maphacks-2.devpost.com\", \"MapHacks 2\") Hackathon, 1st Overall, Best Sustainable Travel Hack",
	"2022 Skills Ontario Coding Competition, 1st"
]

keywords = ["resume", "curriculum vitae", "cv", "software engineer", "developer", "programmer"]

[education]
blurb = "Looking for a *January 2025*, 4-month position"
degree = "Co-op Honours Bachelor of Computer Science"
school = "University of Ottawa"
graduation = "Expected 2026"

[skills]
soft = ["Software Systems", "Programming", "Innovative Thinking"]
technical = [
	"Rust", "TypeScript", "Go", "Python", "Java", "C++", "C", "C#", "Groovy", "PostgreSQL",
	"MySQL", "MongoDB", "Firebase", "Redis", "Memcached", "Qdrant", "InfluxDB", "TimescaleDB",
	"JavaScript", "HTML", "CSS", "Svelte", "Vue", "React", "SvelteKit", "Nuxt", "Next.js",
	"GSAP (GreenSock)", "Flutter", "Express.js", "Fastify", "Axum", "tRPC", "JSONSchema",
	"OpenAPI", "Swagger", "Zod", "Drizzle", "Diesel", "PyTorch", "TensorFlow", "Keras", "Gerrit",
	"Jira", "Confluence", "Skia", "wgpu", "OpenStack", "Docker", "Unity", "Bevy", "Git", "Gerrit",
	"Ansible"
]

[[experience]]
title = "Software Engineer"
company = "Ciena"
location = "Ottawa, ON (Remote)"
start = 2023-05-01
achievements = [
	"Authored a code ownership and test management API with *Express.js*, *Zod*, *Node.js*, and *MongoDB* that improved workflow efficiency and test coverage by 25%.",
	"Developed a log query tool with *Flask*, *Vue*, and *TailwindCSS* that increased error discovery by 30%.",
	"Upgraded and improved a computing management tool with *Python*, *OpenStack*, and *Ansible* that reduced downtime and failures by 15%.",
	"Implemented a full-stack computing resource booking platform with *Vue*, *Nuxt*, *PostgreSQL*, and *tRPC* that reduced resource conflicts by 20%."
]

[[experience]]
title = "STEM Instructor"
company = "RoboEDU"
location = "North York, ON (Remote)"
start = 2022-06-01
end = 2022-08-01
achievements = [
	"Designed engaging course material and led 10-20 students through *Python* and Scratch courses.",
	"Devised a teaching plan to increase student productivity and engagement by 20%."
]

[[project]]
title = "StatPixel"
github = "statpixel-rs/statpixel"
tags = ["Rust", "PostgreSQL", "Redis", "Skia", "WGSL"]
achievements = [
	"Cultivated a community of over 10,000 users to track and visualize their statistics in real time.",
	"Deployed an *image generation* pipeline with *Skia*, generating 500+ daily personalized images.",
	"Organized 2,000+ leaderboards with *Redis* to efficiently retrieve top performers in milliseconds.",
	"Leveraged *code generation* to reduce boilerplate by 90% and improve performance."
]

[[project]]
title = "Basket"
github = "matteopolak/basket"
tags = ["Rust", "HTTP"]
achievements = [
	"Implemented a parser for the *HTTP/1.1* protocol in *Rust* with support for streaming data.",
	"Architected an HTTP client from scratch using *TCP* sockets, exposing a clean public API.",
	"Developed a *multi-threaded HTTP server* with built-in routing support and best-of-class performance."
]

[[project]]
title = "Crave"
github = "matteopolak/crave"
tags = ["Svelte", "TypeScript", "PostgreSQL", "tRPC", "Drizzle", "PyTorch"]
achievements = [
	"Launched a *recipe-sharing* platform with 25 users that creates personalized recommendations.",
	"Integrated a text embedding model with *PyTorch* and *Flask* to vectorize and rank 100,000 recipes.",
	"Designed a user-friendly interface with *DaisyUI* and *TailwindCSS*, improving CTR by 40%."
]
