[about]
name = "Matthew Polak"
phone = "+1 (519) 362-9413"
location = "Ontario, Canada"

email = "me@matteopolak.com"
website = "matteopolak.com"
github = "matteopolak"
linkedin = "matteo-polak"

[education]
blurb = "Looking for a *May 2024*, 4-month position"

