on:
  push:
    branches:
      - main

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Upload PDF to latest release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: resume.pdf
          asset_name: MatthewPolakResume.pdf
          tag: latest
          overwrite: true
