on:
  push:
    branches:
      - main
    paths:
      - "resume.typ"
      - "config.toml"
      - ".github/workflows/build.yml"

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: fontist/setup-fontist@v2
      - run: fontist install "Open Sans"
      - uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: requirements.typ
      - run: typst compile resume.typ MatthewPolakResume.pdf
        env:
          TYPST_FONT_PATHS: ${{ github.workspace }}/fonts
      - uses: softprops/action-gh-release@v2
        with:
          files: MatthewPolakResume.pdf
          name: Latest resume 🎉
          tag_name: latest
          make_latest: true
          generate_release_notes: true

