on:
  push:
    branches:
      - main
    paths:
      - "resume.typ"
      - "config.toml"
      - ".github/workflows/build.yml"

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: requirements.typ
      - run: typst compile resume.typ resume.pdf
        env:
          TYPST_FONT_PATHS: ${{ github.workspace }}/fonts
      - uses: actions/upload-artifact@v4
        with:
          name: MatthewPolakResume
          path: resume.pdf

